apiVersion: batch/v1
kind: Job
metadata:
  name: create-kafka-topic
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: kafka-topic-creator
        image: wurstmeister/kafka:latest
        command:
        - "/bin/bash"
        - "-c"
        - |
          kafka-topics.sh --create --bootstrap-server alco-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092 --replication-factor 3 --partitions 1 --topic iot-anomaly-data
      restartPolicy: Never
  backoffLimit: 4